### ISSUE TITLE
Missing graphqa Folder and Scripts (graph_generator.sh, task_generator.sh) After August Update

### ISSUE THREAD

**Issue by EricLabile** [google-research/talk-like-a-graph#2]
I’m trying to follow the instructions in talk_like_a_graph, which suggest running the following scripts:
```
./graphqa/graph_generator.sh
./graphqa/task_generator.sh
```

However, after the August update, the graphqa folder no longer exists in the repository, and I am unable to locate these scripts. Additionally, older versions of the repository are not accessible to check for the files.

Could you please:
	1.	Clarify if the graphqa folder and these scripts have been removed or replaced.
	2.	Provide access to these 2 files, if possible.

Thank you for your assistance!

**Comment by hxu105** [comment]
Hi Eric, I have met the same issue of missing data and task generator scripts. Do you know where we can find those two scripts? Many thanks!

**Comment by EricLabile** [comment]
> Hi Eric, I have met the same issue of missing data and task generator scripts. Do you know where we can find those two scripts? Many thanks!

It’s under https://github.com/google-research/google-research/tree/master/graphqa
